# Generated by Django 4.0.3 on 2022-04-17 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('username', models.CharField(max_length=64)),
                ('image', models.ImageField(upload_to='images')),
                ('email', models.EmailField(max_length=62)),
            ],
        ),
    ]
